package com.ttaaa.noirgame.domain.model.enumValue

enum class Card(
    val hero: String,
    val group: CardGroup,
) {
    ELLIS("Эллис", CardGroup.MAIN),
    BARRIN("Бэррин", CardGroup.MAIN),
    CLEVE("Клайв", CardGroup.MAIN),
    DEIDRA("Дейдра", CardGroup.MAIN),
    ERNEST("Эрнест", CardGroup.MAIN),
    FRANKLIN("Франклин", CardGroup.MAIN),
    GENEVA("Женева", CardGroup.MAIN),
    HORATIO("Горацио", CardGroup.MAIN),
    IRMA("Ирма", CardGroup.MAIN),
    JULIAN("Джулиан", CardGroup.MAIN),
    CHRISTOPH("Кристоф", CardGroup.MAIN),
    LINUS("Лайнус", CardGroup.MAIN),
    MARION("Мэрион", CardGroup.MAIN),
    NEIL("Нейл", CardGroup.MAIN),
    OFELIA("Офелиа", CardGroup.MAIN),
    PHOEBE("Фиби", CardGroup.MAIN),
    QUINTON("Куинтон", CardGroup.MAIN),
    RYAN("Райан", CardGroup.MAIN),
    SIMON("Саймон", CardGroup.MAIN),
    TREVOR("Тревор", CardGroup.MAIN),
    ULYSSES("Улисс", CardGroup.MAIN),
    VLADIMIR("Владимир", CardGroup.MAIN),
    WILLIAM("Вильгельм", CardGroup.MAIN),
    YVONNE("Ивонн", CardGroup.MAIN),
    ZACHARY("Захари", CardGroup.MAIN),

    ASHTON("Эштон", CardGroup.ADDITIONAL),
    BRANSON("Брэнсон", CardGroup.ADDITIONAL),
    CARTWRIGHT("КАРТРАЙТ", CardGroup.ADDITIONAL),
    DARNELL("Дарнелл", CardGroup.ADDITIONAL),
    EVELYN("Эвелин", CardGroup.ADDITIONAL),
    FLORENCE("Флоренс", CardGroup.ADDITIONAL),
    GRACE("Грейс", CardGroup.ADDITIONAL),
    HUBERT("Хьюберт", CardGroup.ADDITIONAL),
    IVAN("Иван", CardGroup.ADDITIONAL),
    JACK("Джек", CardGroup.ADDITIONAL),
    CATHERINE("Кэтрин", CardGroup.ADDITIONAL),
    LINNET("Линнет", CardGroup.ADDITIONAL),
    MARCUS("Маркус", CardGroup.ADDITIONAL),
    NATHAN("Натан", CardGroup.ADDITIONAL),
    DRUZHOK("Дружок", CardGroup.ADDITIONAL),
    PEDRO("Педро", CardGroup.ADDITIONAL),
    QASIM("Касим", CardGroup.ADDITIONAL),
    RAMON("Рамон", CardGroup.ADDITIONAL),
    SUZANNA("Сюзанна", CardGroup.ADDITIONAL),
    TASHA("Таша", CardGroup.ADDITIONAL),
    ULBRECHT("Ульбрехт", CardGroup.ADDITIONAL),
    WINSAN("Винсан", CardGroup.ADDITIONAL),
    WANDA("Ванда", CardGroup.ADDITIONAL),
    ISOLDE("Изольда", CardGroup.ADDITIONAL),
    XAVIER("Ксавье", CardGroup.ADDITIONAL),
}