package com.ttaaa.noirgame.domain.model.enumValue

enum class Card(
    val person: String,
    val group: CardGroup,
) {
    ELLIS("Эллис", CardGroup.GAME_5X5),
    BARRIN("Бэррин", CardGroup.GAME_5X5),
    CLEVE("Клайв", CardGroup.GAME_5X5),
    DEIDRA("Дейдра", CardGroup.GAME_5X5),
    ERNEST("Эрнест", CardGroup.GAME_5X5),
    FRANKLIN("Франклин", CardGroup.GAME_5X5),
    GENEVA("Женева", CardGroup.GAME_5X5),
    HORATIO("Горацио", CardGroup.GAME_5X5),
    IRMA("Ирма", CardGroup.GAME_5X5),
    JULIAN("Джулиан", CardGroup.GAME_5X5),
    CHRISTOPH("Кристоф", CardGroup.GAME_5X5),
    LINUS("Лайнус", CardGroup.GAME_5X5),
    MARION("Мэрион", CardGroup.GAME_5X5),
    NEIL("Нейл", CardGroup.GAME_5X5),
    OFELIA("Офелиа", CardGroup.GAME_5X5),
    PHOEBE("Фиби", CardGroup.GAME_5X5),
    QUINTON("Куинтон", CardGroup.GAME_5X5),
    RYAN("Райан", CardGroup.GAME_5X5),
    SIMON("Саймон", CardGroup.GAME_5X5),
    TREVOR("Тревор", CardGroup.GAME_5X5),
    ULYSSES("Улисс", CardGroup.GAME_5X5),
    VLADIMIR("Владимир", CardGroup.GAME_5X5),
    WILLIAM("Вильгельм", CardGroup.GAME_5X5),
    YVONNE("Ивонн", CardGroup.GAME_5X5),
    ZACHARY("Захари", CardGroup.GAME_5X5),

    ASHTON("Эштон", CardGroup.GAME_6X6),
    BRANSON("Брэнсон", CardGroup.GAME_6X6),
    CARTWRIGHT("Картрайт", CardGroup.GAME_6X6),
    DARNELL("Дарнелл", CardGroup.GAME_6X6),
    EVELYN("Эвелин", CardGroup.GAME_6X6),
    FLORENCE("Флоренс", CardGroup.GAME_6X6),
    GRACE("Грейс", CardGroup.GAME_6X6),
    HUBERT("Хьюберт", CardGroup.GAME_6X6),
    IVAN("Иван", CardGroup.GAME_6X6),
    JACK("Джек", CardGroup.GAME_6X6),
    CATHERINE("Кэтрин", CardGroup.GAME_6X6),

    LINNET("Линнет", CardGroup.GAME_7X7),
    MARCUS("Маркус", CardGroup.GAME_7X7),
    NATHAN("Натан", CardGroup.GAME_7X7),
    DRUZHOK("Дружок", CardGroup.GAME_7X7),
    PEDRO("Педро", CardGroup.GAME_7X7),
    QASIM("Касим", CardGroup.GAME_7X7),
    RAMON("Рамон", CardGroup.GAME_7X7),
    SUZANNA("Сюзанна", CardGroup.GAME_7X7),
    TASHA("Таша", CardGroup.GAME_7X7),
    ULBRECHT("Ульбрехт", CardGroup.GAME_7X7),
    WINSAN("Винсан", CardGroup.GAME_7X7),
    WANDA("Ванда", CardGroup.GAME_7X7),
    ISOLDE("Изольда", CardGroup.GAME_7X7),
}